spring:
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
taco:
  orders:
    pageSize: 10